name: new_u
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  video_player: ^2.10.0
  google_fonts: ^6.3.0
  flutter_cache_manager: ^3.4.1
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5
  chewie: ^1.12.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  just_audio: ^0.10.4
  audioplayers: ^6.5.0
  media_kit: ^1.2.0
  better_player: ^0.0.84
  media_kit_video: ^1.3.0
  media_kit_libs_android_video: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/video/
    - assets/audio/
